name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Depend Packages
      run: |
        sudo apt install python2.7 python-pip gcc-arm-none-eabi mercurial git
        which arm-none-eabi-gcc
    - name: Install Mbed CLI
      run: |
        sudo pip install mbed-cli
        sudo pip install -r mbed-os/requirements.txt
    - name: Install External Libraries
      run: |
        mbed deploy
    - name: build
      run: |
        mbed compile
