name: build

on: [push]

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Depend Packages
      run: |
        sudo apt install python2.7 python-pip gcc-arm-none-eabi mercurial git
        which arm-none-eabi-gcc
    - name: Install and Config Mbed CLI
      run: |
        sudo pip install mbed-cli
        sudo pip install jsonschema paramiko pyelftools
        sudo pip install -r requirements.txt
        mbed config --global GCC_ARM_PATH "/usr/bin/"
    - name: Build
      run: ./ci.sh
